### ISSUE TITLE
"mkchain my-chain" in the readme fails - needs updating

### ISSUE THREAD

**Issue by brandisimus** [tqtezos/tezos-k8s#66]
The readme quickstart section of the readme contains the following:
```
mkchain my-chain
```
which when executed as instructed fails with the following message:
```
mkchain my-chain
usage: mkchain [-h] [--version] {generate-constants,create,invite} ...
mkchain: error: argument action: invalid choice: 'mkchain' (choose from 'generate-constants', 'create', 'invite')
```
The readme needs updating

**Comment by brandisimus** [comment]
Attempting to use `mkchain generate-constants andrey-chain` results in the error:

```
Traceback (most recent call last):
  File "/Users/andrey/Documents/TQ/tezos-k8s/.venv/bin/mkchain", line 8, in <module>
    sys.exit(main())
  File "/Users/andrey/Documents/TQ/tezos-k8s/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 329, in main
    keys = gen_key(args.docker_image)
  File "/Users/andrey/Documents/TQ/tezos-k8s/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 48, in gen_key
    "secret_key": keys[2].split(b":")[2].strip().decode("utf-8"),
```

**Comment by brandisimus** [comment]
This has been done
