### ISSUE TITLE
mkchain fails to run minikube's docker

### ISSUE THREAD

**Issue by brandisimus** [tqtezos/tezos-k8s#71]
https://github.com/tqtezos/tezos-k8s/blob/0b2ed250ae44ec23f492533130081dc511c1ecb5/mkchain/tqchain/mkchain.py#L31

executing the following
```
mkchain $CHAIN_NAME --zerotier-network $ZT_NET --zerotier-token $ZT_TOKEN
```
results in the error
```
bozon@buba test % minikube start       
😄  minikube v1.16.0 on Darwin 11.1
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
bozon@buba test % eval $(minikube docker-env)
bozon@buba test % mkdir mkchain && cd mkchain
python3 -m venv .venv
source .venv/bin/activate

(.venv) bozon@buba mkchain % 
(.venv) bozon@buba mkchain % pip install mkchain==0.0.1
Collecting mkchain==0.0.1
  Using cached mkchain-0.0.1-py3-none-any.whl (5.0 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Using legacy 'setup.py install' for pyyaml, since package 'wheel' is not installed.
Installing collected packages: pyyaml, mkchain
    Running setup.py install for pyyaml ... done
Successfully installed mkchain-0.0.1 pyyaml-5.3.1
WARNING: You are using pip version 20.2.3; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/bozon/Documents/TQ/test/mkchain/.venv/bin/python3 -m pip install --upgrade pip' command.
(.venv) bozon@buba mkchain % export PYTHONUNBUFFERED=x
(.venv) bozon@buba mkchain % export CHAIN_NAME=avb     
(.venv) bozon@buba mkchain % mkchain $CHAIN_NAME --zerotier-network $ZT_NET --zerotier-token $ZT_TOKEN
Traceback (most recent call last):
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/bin/mkchain", line 8, in <module>
    sys.exit(main())
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 125, in main
    "genesis_chain_id": get_genesis_vanity_chain_id(),
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 48, in get_genesis_vanity_chain_id
    run_docker(
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 19, in run_docker
    return subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker run --entrypoint flextesa --rm registry.gitlab.com/tezos/flextesa:01e3f596-run vani "" --seed 4X4M58LLL043JZWS --first --machine-readable csv' returned non-zero exit status 127.
```

**Comment by brandisimus** [comment]
I don't think 'eval $(minikube docker-env)' does what it intends to do. In an attempt to address the error above I run
```
brew install docker
brew link docker
```
and it seemed to have solved the immediate problem and progressed further to the following error:
```
(.venv) bozon@buba mkchain % mkchain $CHAIN_NAME --zerotier-network $ZT_NET --zerotier-token $ZT_TOKEN
Traceback (most recent call last):
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/bin/mkchain", line 8, in <module>
    sys.exit(main())
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 141, in main
    keys = gen_key(args.docker_image)
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 38, in gen_key
    return {"public_key": extract_key(keys, 1), "secret_key": extract_key(keys, 2)}
  File "/Users/bozon/Documents/TQ/test/mkchain/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 27, in extract_key
    return keys[index].split(b":")[index].strip().decode("ascii")
IndexError: list index out of range
```

**Comment by brandisimus** [comment]
This 'index out of range' error might be a different issue from what was originally reported here. In any case this problem seem to appear intermittently, got it again today:
```
(.venv) bozon@blob aryeh % mkchain --docker-image tezos/tezos:v8-release av8            
Traceback (most recent call last):
  File "/Users/bozon/Documents/TQ/aryeh/.venv/bin/mkchain", line 8, in <module>
    sys.exit(main())
  File "/Users/bozon/Documents/TQ/aryeh/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 141, in main
    keys = gen_key(args.docker_image)
  File "/Users/bozon/Documents/TQ/aryeh/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 38, in gen_key
    return {"public_key": extract_key(keys, 1), "secret_key": extract_key(keys, 2)}
  File "/Users/bozon/Documents/TQ/aryeh/.venv/lib/python3.9/site-packages/tqchain/mkchain.py", line 27, in extract_key
    return keys[index].split(b":")[index].strip().decode("ascii")
IndexError: list index out of range
```
